import assert from "node:assert/strict";
import test, { after, afterEach } from "node:test";
import bcrypt from "bcrypt";
import request from "supertest";
import app from "../src/app";
import { pool } from "../src/config/db";
import { clearCapturedOtpsForTest, getCapturedOtpForTest } from "../src/services/email.service";
import { cleanupTestData } from "./test-helpers";
process.env.NODE_ENV = "test";
const prefix = `p9${Date.now().toString(36)}`, email = `${prefix}.customer@example.com`, password = "Phase9@Bank123";
const auth = (token: string) => ({ Authorization: `Bearer ${token}` });
let adminToken = "", customerToken = "", customerId = "", userId = "", customerNumber = "", branchId = "", sourceId = "", destinationId = "", zeroId = "", loanRequestId = "", loanId = "", loanAccountId = "", firstEmiId = "";
async function admin() { if (adminToken)
    return adminToken; const res = await request(app).post("/api/v1/auth/login").send({ customerId: "ADMINLOCAL0001", password: "PiBank@Admin001" }); assert.equal(res.status, 200); adminToken = res.body.data.token; return adminToken; }
async function approvedAccount(type: "SAVINGS" | "CURRENT", subtype: string) { const created = await request(app).post("/api/v1/account-requests").set(auth(customerToken)).send({ accountType: type, accountSubtype: subtype, preferredBranchId: branchId, purpose: "Phase 9 verification account", requestedPerTransactionLimit: 5000, requestedDailyTransferLimit: 10000 }); assert.equal(created.status, 201); const id = created.body.data.account_request_id; assert.equal((await request(app).post(`/api/v1/admin/account-requests/${id}/review`).set(auth(await admin()))).status, 200); const approved = await request(app).post(`/api/v1/admin/account-requests/${id}/approve`).set(auth(await admin())).send({ approvedBranchId: branchId, approvedPerTransactionLimit: 5000, approvedDailyTransferLimit: 10000 }); assert.equal(approved.status, 200); return String(approved.body.data.account.account_id); }
after(async () => { clearCapturedOtpsForTest(); const users = await pool.query<{
    user_id: string;
}>("SELECT user_id::text FROM users WHERE email LIKE $1", [`${prefix}%`]); const userIds = users.rows.map(x => x.user_id); const customers = await pool.query<{
    customer_id: string;
}>("SELECT customer_id::text FROM customers WHERE email LIKE $1", [`${prefix}%`]); const customerIds = customers.rows.map(x => x.customer_id); if (customerIds.length) {
    const loans = await pool.query<{
        loan_id: string;
        loan_request_id: string;
    }>("SELECT loan_id::text,loan_request_id::text FROM loans WHERE customer_id=ANY($1::bigint[])", [customerIds]);
    const loanIds = loans.rows.map(x => x.loan_id), requestIds = loans.rows.map(x => x.loan_request_id);
    if (loanIds.length) {
        await pool.query("DELETE FROM loan_emi_schedules WHERE loan_id=ANY($1::bigint[])", [loanIds]);
        await pool.query("DELETE FROM audit_logs WHERE entity='LOAN' AND entity_id=ANY($1::bigint[])", [loanIds]);
        await pool.query("DELETE FROM loans WHERE loan_id=ANY($1::bigint[])", [loanIds]);
    }
    if (requestIds.length) {
        await pool.query("DELETE FROM request_status_history WHERE request_type='LOAN' AND request_id=ANY($1::bigint[])", [requestIds]);
        await pool.query("DELETE FROM audit_logs WHERE entity='LOAN_REQUEST' AND entity_id=ANY($1::bigint[])", [requestIds]);
    }
} if (userIds.length)
    await pool.query("DELETE FROM request_status_history WHERE changed_by=ANY($1::bigint[])", [userIds]); await cleanupTestData(prefix); await pool.end(); });
afterEach(async (context) => {
    if (!context.name.startsWith("9 "))
        return;
    const audit = await pool.query<{ action: string }>(`SELECT action FROM audit_logs
         WHERE (entity = 'CUSTOMER' AND entity_id = $1)
            OR (entity = 'ACCOUNT' AND entity_id = ANY($2::bigint[]))
            OR (entity = 'LOAN' AND entity_id = $3)`, [customerId, [sourceId, zeroId], loanId]);
    const actions = new Set(audit.rows.map((row) => row.action));
    for (const action of [
        "CUSTOMER_APPROVED", "CUSTOMER_BLOCKED", "CUSTOMER_UNBLOCKED",
        "ACCOUNT_FROZEN", "ACCOUNT_UNFROZEN", "ACCOUNT_CLOSED",
        "LOAN_APPROVED", "LOAN_DISBURSED", "LOAN_EMI_PAID",
        "LOAN_PREPAID", "LOAN_FORECLOSED",
    ])
        assert.ok(actions.has(action), `Missing audit action ${action}`);
});
test("1 registration OTP KYC approval customer login and block lifecycle", async () => { const started = await request(app).post("/api/v1/auth/register").send({ firstName: "Phase", lastName: "Nine", dateOfBirth: "1992-06-18", mobile: "9876500009", email }); assert.equal(started.status, 201); const otp = getCapturedOtpForTest(email); assert.match(otp ?? "", /^\d{6}$/); const verified = await request(app).post("/api/v1/auth/verify-otp").send({ email, otp }); assert.equal(verified.status, 200); const completed = await request(app).post("/api/v1/auth/complete-registration").send({ registrationToken: verified.body.data.registrationToken, password, confirmPassword: password }); assert.equal(completed.status, 201); customerNumber = completed.body.data.customerId; let login = await request(app).post("/api/v1/auth/login").send({ customerId: customerNumber, password }); assert.equal(login.status, 403); const row = await pool.query("SELECT c.customer_id::text,c.user_id::text,c.branch_id::text FROM customers c WHERE c.customer_number=$1", [customerNumber]); customerId = row.rows[0].customer_id; userId = row.rows[0].user_id; branchId = row.rows[0].branch_id; assert.equal((await request(app).patch(`/api/v1/admin/customers/${customerId}/kyc`).set(auth(await admin())).send({ status: "VERIFIED" })).status, 200); assert.equal((await request(app).post(`/api/v1/admin/customers/${customerId}/approve`).set(auth(await admin()))).status, 200); login = await request(app).post("/api/v1/auth/login").send({ customerId: customerNumber, password }); assert.equal(login.status, 200); customerToken = login.body.data.token; assert.equal((await request(app).post(`/api/v1/admin/customers/${customerId}/block`).set(auth(await admin())).send({ reason: "Phase 9 security check" })).status, 200); assert.equal((await request(app).post("/api/v1/auth/login").send({ customerId: customerNumber, password })).status, 403); assert.equal((await request(app).post(`/api/v1/admin/customers/${customerId}/unblock`).set(auth(await admin()))).status, 200); login = await request(app).post("/api/v1/auth/login").send({ customerId: customerNumber, password }); assert.equal(login.status, 200); customerToken = login.body.data.token; });
test("2 account request approval creates immutable zero-balance account", async () => { const bypass = await request(app).post("/api/v1/accounts").set(auth(customerToken)).send({ accountType: "SAVINGS" }); assert.equal(bypass.status, 404); sourceId = await approvedAccount("SAVINGS", "REGULAR"); destinationId = await approvedAccount("CURRENT", "STANDARD"); const row = await pool.query("SELECT account_type::text,account_subtype,branch_id::text,ifsc_code,current_balance::text,available_balance::text,per_transaction_limit::text,daily_transfer_limit::text FROM accounts WHERE account_id=$1", [sourceId]); assert.equal(row.rows[0].account_type, "SAVINGS"); assert.equal(row.rows[0].account_subtype, "REGULAR"); assert.equal(row.rows[0].branch_id, branchId); assert.match(row.rows[0].ifsc_code, /^PIBK/); assert.equal(Number(row.rows[0].current_balance), 0); assert.equal(Number(row.rows[0].available_balance), 0); assert.equal(Number(row.rows[0].per_transaction_limit), 5000); });
test("3 transfer within limits reconciles transaction ledger and balances", async () => { assert.equal((await request(app).post("/api/v1/transactions/deposit").set(auth(customerToken)).send({ accountId: sourceId, amount: 1000 })).status, 201); const before = await pool.query("SELECT current_balance::text FROM accounts WHERE account_id IN($1,$2) ORDER BY account_id", [sourceId, destinationId]); const transfer = await request(app).post("/api/v1/transfers").set(auth(customerToken)).send({ sourceAccountId: sourceId, destinationAccountId: destinationId, amount: 100, remarks: "Phase 9 balanced transfer" }); assert.equal(transfer.status, 201); const ledger = await pool.query("SELECT entry_type,amount::text,balance_before::text,balance_after::text FROM ledger_entries WHERE transaction_id=$1 ORDER BY entry_type", [transfer.body.data.transaction_id]); assert.equal(ledger.rowCount, 2); assert.deepEqual(ledger.rows.map(x => x.entry_type).sort(), ["CREDIT", "DEBIT"]); assert.equal(ledger.rows[0].amount, ledger.rows[1].amount); for (const entry of ledger.rows)
    assert.equal(Number(entry.balance_after), Number(entry.balance_before) + (entry.entry_type === "CREDIT" ? Number(entry.amount) : -Number(entry.amount))); const afterRows = await pool.query("SELECT current_balance::text FROM accounts WHERE account_id IN($1,$2) ORDER BY account_id", [sourceId, destinationId]); assert.equal(afterRows.rows.reduce((s, x) => s + Number(x.current_balance), 0), before.rows.reduce((s, x) => s + Number(x.current_balance), 0)); });
test("4 transfer limits reject before financial posting", async () => { const created = await request(app).post("/api/v1/transfer-limit-requests").set(auth(customerToken)).send({ accountId: sourceId, requestedPerTransactionLimit: 50, requestedDailyTransferLimit: 100, reason: "Phase 9 limit check" }); assert.equal(created.status, 201); const id = created.body.data.transfer_limit_request_id; await request(app).post(`/api/v1/admin/transfer-limit-requests/${id}/review`).set(auth(await admin())); assert.equal((await request(app).post(`/api/v1/admin/transfer-limit-requests/${id}/approve`).set(auth(await admin()))).status, 200); const before = await pool.query("SELECT current_balance::text,(SELECT count(*)::int FROM transactions) tx_count FROM accounts WHERE account_id=$1", [sourceId]); const blocked = await request(app).post("/api/v1/transfers").set(auth(customerToken)).send({ sourceAccountId: sourceId, destinationAccountId: destinationId, amount: 60 }); assert.equal(blocked.status, 409); assert.equal(blocked.body.error.code, "TRANSFER_PER_TRANSACTION_LIMIT_EXCEEDED"); const afterState = await pool.query("SELECT current_balance::text,(SELECT count(*)::int FROM transactions) tx_count FROM accounts WHERE account_id=$1", [sourceId]); assert.deepEqual(afterState.rows[0], before.rows[0]); });
test("5 freeze and unfreeze block activity and preserve manual card blocks", async () => { const auto = await request(app).post("/api/v1/cards").set(auth(customerToken)).send({ accountId: sourceId, cardType: "DEBIT" }); const manual = await request(app).post("/api/v1/cards").set(auth(customerToken)).send({ accountId: sourceId, cardType: "DEBIT" }); assert.equal(auto.status, 201); assert.equal(manual.status, 201); await request(app).patch(`/api/v1/cards/${manual.body.data.card_id ?? manual.body.data.cardId}/block`).set(auth(customerToken)); assert.equal((await request(app).post(`/api/v1/admin/accounts/${sourceId}/freeze`).set(auth(await admin())).send({ reason: "Phase 9 freeze test" })).status, 200); assert.equal((await request(app).post("/api/v1/transactions/withdraw").set(auth(customerToken)).send({ accountId: sourceId, amount: 1 })).status, 409); assert.equal((await request(app).post(`/api/v1/admin/accounts/${sourceId}/unfreeze`).set(auth(await admin())).send({ reason: "Phase 9 unfreeze test" })).status, 200); const cards = await pool.query("SELECT card_status,freeze_source FROM cards WHERE account_id=$1 ORDER BY card_id", [sourceId]); assert.deepEqual(cards.rows.map(x => [x.card_status, x.freeze_source]), [["ACTIVE", null], ["BLOCKED", "MANUAL"]]); });
test("6 account closure validates balance and closes eligible relationships", async () => { let created = await request(app).post("/api/v1/account-closure-requests").set(auth(customerToken)).send({ accountId: destinationId, reason: "Non-zero closure verification" }); let id = created.body.data.account_closure_request_id; await request(app).post(`/api/v1/admin/account-closure-requests/${id}/review`).set(auth(await admin())); const denied = await request(app).post(`/api/v1/admin/account-closure-requests/${id}/approve`).set(auth(await admin())); assert.equal(denied.status, 409); assert.equal(denied.body.error.code, "ACCOUNT_CANNOT_CLOSE_WITH_BALANCE"); zeroId = await approvedAccount("CURRENT", "ZERO_CLOSE"); const account = await pool.query("SELECT account_number FROM accounts WHERE account_id=$1", [zeroId]); await request(app).post("/api/v1/cards").set(auth(customerToken)).send({ accountId: zeroId, cardType: "DEBIT" }); await request(app).post("/api/v1/beneficiaries").set(auth(customerToken)).send({ beneficiaryName: "Closure Target", beneficiaryAccountNo: account.rows[0].account_number, bankName: "Pi Bank", bankCode: "PIBK001" }); created = await request(app).post("/api/v1/account-closure-requests").set(auth(customerToken)).send({ accountId: zeroId, reason: "Eligible zero balance closure" }); id = created.body.data.account_closure_request_id; await request(app).post(`/api/v1/admin/account-closure-requests/${id}/review`).set(auth(await admin())); assert.equal((await request(app).post(`/api/v1/admin/account-closure-requests/${id}/approve`).set(auth(await admin()))).status, 200); const state = await pool.query("SELECT (SELECT account_status FROM accounts WHERE account_id=$1) account_status,(SELECT card_status FROM cards WHERE account_id=$1 LIMIT 1) card_status,(SELECT status FROM beneficiaries WHERE beneficiary_account_no=$2 LIMIT 1) beneficiary_status", [zeroId, account.rows[0].account_number]); assert.deepEqual(state.rows[0], { account_status: "CLOSED", card_status: "CLOSED", beneficiary_status: "INACTIVE" }); });
test("7 loan approval is separate from one-time disbursement and creates EMI schedule", async () => { const created = await request(app).post("/api/v1/loan-requests").set(auth(customerToken)).send({ requestedAmount: 3000, durationMonths: 3, loanType: "PERSONAL", loanSubtype: "UNSECURED_PERSONAL", purpose: "Phase 9 loan verification" }); assert.equal(created.status, 201); loanRequestId = created.body.data.loan_request_id; await request(app).post(`/api/v1/admin/loan-requests/${loanRequestId}/review`).set(auth(await admin())); const before = await pool.query("SELECT current_balance::text FROM accounts WHERE account_id=$1", [sourceId]); const approved = await request(app).post(`/api/v1/admin/loan-requests/${loanRequestId}/approve`).set(auth(await admin())).send({ approvedAmount: 3000, approvedDurationMonths: 3, approvedInterestRate: 12 }); assert.equal(approved.status, 200); loanId = approved.body.data.loan.loan_id; loanAccountId = approved.body.data.loanAccount.account_id; assert.equal((await pool.query("SELECT count(*)::int count FROM loan_emi_schedules WHERE loan_id=$1", [loanId])).rows[0].count, 0); assert.equal((await pool.query("SELECT current_balance::text FROM accounts WHERE account_id=$1", [sourceId])).rows[0].current_balance, before.rows[0].current_balance); const disbursed = await request(app).post(`/api/v1/admin/loans/${loanId}/disburse`).set(auth(await admin())).send({ destinationAccountId: sourceId }); assert.equal(disbursed.status, 200); assert.equal((await request(app).post(`/api/v1/admin/loans/${loanId}/disburse`).set(auth(await admin())).send({ destinationAccountId: sourceId })).status, 409); const schedule = await pool.query("SELECT emi_schedule_id::text,principal_component::text FROM loan_emi_schedules WHERE loan_id=$1 ORDER BY installment_number", [loanId]); assert.equal(schedule.rowCount, 3); firstEmiId = schedule.rows[0].emi_schedule_id; assert.ok(Math.abs(schedule.rows.reduce((s, x) => s + Number(x.principal_component), 0) - 3000) < 0.001); });
test("8 EMI prepayment and foreclosure preserve financial integrity", async () => { assert.equal((await request(app).post(`/api/v1/loans/${loanId}/emis/${firstEmiId}/pay`).set(auth(customerToken)).send({ sourceAccountId: sourceId })).status, 201); assert.equal((await request(app).post(`/api/v1/loans/${loanId}/prepay`).set(auth(customerToken)).send({ sourceAccountId: sourceId, amount: 200 })).status, 201); assert.equal((await request(app).post(`/api/v1/loans/${loanId}/foreclose`).set(auth(customerToken)).send({ sourceAccountId: sourceId })).status, 201); const loan = await pool.query("SELECT status,outstanding_principal::text FROM loans WHERE loan_id=$1", [loanId]); assert.deepEqual(loan.rows[0], { status: "FORECLOSED", outstanding_principal: "0.0000" }); const history = await pool.query("SELECT status FROM loan_emi_schedules WHERE loan_id=$1", [loanId]); assert.ok(history.rows.some(x => x.status === "PAID")); assert.ok(history.rows.some(x => x.status === "CANCELLED")); const invalid = await pool.query("SELECT 1 FROM ledger_entries WHERE amount<=0 OR entry_type NOT IN('DEBIT','CREDIT') OR (entry_type='DEBIT' AND balance_after<>balance_before-amount) OR (entry_type='CREDIT' AND balance_after<>balance_before+amount) LIMIT 1"); assert.equal(invalid.rowCount, 0); });
test("9 customer admin separation and cross-customer ownership protection", async () => { assert.equal((await request(app).get("/api/v1/admin/customers").set(auth(customerToken))).status, 403); const hash = await bcrypt.hash(password, 10); const otherUser = await pool.query("INSERT INTO users(email,password_hash,role,status,email_verified,email_verified_at) VALUES($1,$2,'CUSTOMER','ACTIVE',true,now()) RETURNING user_id::text", [`${prefix}.other@example.com`, hash]); const otherCustomer = await pool.query("INSERT INTO customers(user_id,branch_id,customer_number,first_name,last_name,email,customer_status,kyc_status) VALUES($1,$2,$3,'Other','Customer',$4,'ACTIVE','VERIFIED') RETURNING customer_id::text", [otherUser.rows[0].user_id, branchId, `${customerNumber}B`, `${prefix}.other@example.com`]); const otherAccount = await pool.query("INSERT INTO accounts(account_number,customer_id,branch_id,account_type,currency,current_balance,available_balance,account_status,opened_at) VALUES($1,$2,$3,'SAVINGS','INR',0,0,'ACTIVE',CURRENT_DATE) RETURNING account_id::text", [`${prefix}other`.slice(0, 20), otherCustomer.rows[0].customer_id, branchId]); assert.equal((await request(app).get(`/api/v1/accounts/${otherAccount.rows[0].account_id}`).set(auth(customerToken))).status, 404); assert.equal((await request(app).post("/api/v1/transfers").set(auth(customerToken)).send({ sourceAccountId: otherAccount.rows[0].account_id, destinationAccountId: sourceId, amount: 1 })).status, 403); assert.equal((await request(app).get(`/api/v1/loans/${loanId}`).set(auth((await request(app).post("/api/v1/auth/login").send({ customerId: `${customerNumber}B`, password })).body.data.token))).status, 404); });
test("10 customer and admin route/auth hydration regression wiring", async () => { const { readFile } = await import("node:fs/promises"); const appSource = await readFile(new URL("../../frontend/src/app.tsx", import.meta.url), "utf8"); const authStore = await readFile(new URL("../../frontend/src/stores/auth.store.ts", import.meta.url), "utf8"); assert.match(appSource, /ProtectedRoute/); assert.match(appSource, /AdminRoute/); for (const route of ["dashboard", "accounts", "transfer", "transactions", "beneficiaries", "cards", "loans", "settings", "admin/customers", "admin/accounts"])
    assert.match(appSource, new RegExp(route)); assert.match(authStore, /persist/); assert.doesNotMatch(authStore, /password|otp/i); });
