import { FormEvent, type ReactNode } from "react";
import { LoaderCircle, X } from "lucide-react";

export const inr = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 });
export const dateTime = (value?: string | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
export function StatusBadge({ value }: { value: string }) { const good = ["ACTIVE", "APPROVED", "COMPLETED", "PAID", "VERIFIED"].includes(value); const bad = ["BLOCKED", "FROZEN", "REJECTED", "OVERDUE", "CLOSED"].includes(value); return <span className={`inline-flex rounded-full px-2.5 py-1 text-[9px] font-extrabold ${good ? "bg-emerald-50 text-emerald-700" : bad ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{value}</span>; }
export function AdminModal({ title, subtitle, children, pending, error, submitLabel, onClose, onSubmit }: { title: string; subtitle?: string; children?: ReactNode; pending: boolean; error?: string; submitLabel: string; onClose: () => void; onSubmit: (values: Record<string, string>) => void }) {
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); onSubmit(Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string, string>); }
  return <div className="fixed inset-0 z-50 grid place-items-center bg-bank-dark/45"><form onSubmit={submit} className="w-[500px] rounded-2xl bg-white p-6 shadow-2xl"><button type="button" onClick={onClose} className="float-right text-bank-muted"><X size={18} /></button><h2 className="text-lg font-extrabold text-bank-navy">{title}</h2>{subtitle ? <p className="mt-1 text-xs text-bank-muted">{subtitle}</p> : null}<div className="mt-5 space-y-4">{children}</div>{error ? <p className="mt-4 rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p> : null}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="h-10 rounded-lg border border-bank-border px-4 text-xs font-bold">Cancel</button><button disabled={pending} className="inline-flex h-10 items-center gap-2 rounded-lg bg-bank-blue px-5 text-xs font-bold text-white disabled:opacity-60">{pending && <LoaderCircle size={14} className="animate-spin" />}{submitLabel}</button></div></form></div>;
}
export function Field({ name, label, type = "text", defaultValue, required = true, min, max, step, minLength, maxLength }: { name: string; label: string; type?: string; defaultValue?: string | number; required?: boolean; min?: number; max?: number; step?: number | string; minLength?: number; maxLength?: number }) { return <label className="block text-[11px] font-bold text-bank-navy">{label}<input name={name} type={type} defaultValue={defaultValue} required={required} min={min} max={max} step={step} minLength={minLength} maxLength={maxLength} className="mt-1.5 h-10 w-full rounded-lg border border-bank-border px-3 text-xs font-normal outline-none focus:border-bank-blue" /></label>; }
export function SelectField({ name, label, defaultValue, children }: { name: string; label: string; defaultValue?: string; children: ReactNode }) { return <label className="block text-[11px] font-bold text-bank-navy">{label}<select name={name} defaultValue={defaultValue} required className="mt-1.5 h-10 w-full rounded-lg border border-bank-border px-3 text-xs font-normal">{children}</select></label>; }
export const actionButton = "rounded-md border border-bank-border px-2.5 py-1.5 text-[10px] font-bold text-bank-navy hover:border-bank-blue hover:text-bank-blue disabled:opacity-50";
