import { FormEvent, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, Eye, LoaderCircle, Pencil, Plus, Search, X } from "lucide-react";
import { adminApi, type AdminList, type AdminQuery } from "@/api/adminApi";
import { AdminLayout } from "@/components/admin/admin-layout";
import { getApiErrorMessage } from "@/lib/apiClient";
import { downloadCsv, reportDate } from "@/lib/csv";

export type AdminResource = "customers" | "accounts" | "transactions" | "employees" | "branches" | "atms" | "cards" | "audit-logs";
const meta: Record<AdminResource, { title: string; subtitle: string; search: string }> = {
  customers: { title: "Customers", subtitle: "Customer identity, access status, and accounts", search: "Customer ID, name, or email" },
  accounts: { title: "Accounts", subtitle: "Balances and operational account status", search: "Account, owner, or Customer ID" },
  transactions: { title: "Transactions", subtitle: "Read-only bank-wide transaction monitoring", search: "Reference or account number" },
  employees: { title: "Employees", subtitle: "Branch employee administration", search: "Employee number, name, or email" },
  branches: { title: "Branches", subtitle: "Branch managers and operating footprint", search: "Branch code, name, or city" },
  atms: { title: "ATMs", subtitle: "ATM estate and availability", search: "ATM code, location, or branch" },
  cards: { title: "Cards", subtitle: "Masked card inventory and status", search: "Card reference, account, or Customer ID" },
  "audit-logs": { title: "Audit Logs", subtitle: "Immutable record of important system actions", search: "User, action, or entity" },
};
const inr = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 });
const dateTime = (value?: string | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";

function Status({ value }: { value: string }) {
  const active = value === "ACTIVE" || value === "COMPLETED";
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-[9px] font-extrabold ${active ? "bg-emerald-50 text-emerald-700" : value === "FROZEN" || value === "BLOCKED" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{value}</span>;
}

function EmployeeModal({ open, branches, pending, error, onClose, onSubmit }: { open: boolean; branches: any[]; pending: boolean; error?: string | undefined; onClose: () => void; onSubmit: (data: Record<string, string>) => void }) {
  if (!open) return null;
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = Object.fromEntries([...new FormData(event.currentTarget).entries()].filter(([, value]) => String(value).trim())) as Record<string, string>;
    onSubmit(data);
  }
  return <div className="fixed inset-0 z-50 grid place-items-center bg-bank-dark/45"><form onSubmit={submit} className="w-[520px] rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-lg font-extrabold text-bank-navy">Create Employee</h2><p className="text-xs text-bank-muted">Assign the employee to an existing branch.</p></div><button type="button" onClick={onClose}><X size={18} /></button></div><div className="mt-5 grid grid-cols-2 gap-4">{[["firstName","First name"],["lastName","Last name"],["employeeNumber","Employee number"],["position","Position"],["email","Email"],["phone","Phone"]].map(([name,label]) => <label key={name} className="text-[11px] font-bold text-bank-navy">{label}<input name={name} required={!['email','phone','position'].includes(name)} className="mt-1.5 h-10 w-full rounded-lg border border-bank-border px-3 text-xs font-normal outline-none focus:border-bank-blue" /></label>)}<label className="col-span-2 text-[11px] font-bold text-bank-navy">Branch<select name="branchId" required className="mt-1.5 h-10 w-full rounded-lg border border-bank-border px-3 text-xs font-normal"><option value="">Select branch</option>{branches.map((branch) => <option key={branch.branchId} value={branch.branchId}>{branch.branchName} ({branch.branchCode})</option>)}</select></label></div>{error ? <p className="mt-3 text-xs text-red-600">{error}</p> : null}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="h-10 rounded-lg border border-bank-border px-4 text-xs font-bold">Cancel</button><button disabled={pending} className="inline-flex h-10 items-center gap-2 rounded-lg bg-bank-blue px-5 text-xs font-bold text-white disabled:opacity-60">{pending && <LoaderCircle size={14} className="animate-spin" />}Create Employee</button></div></form></div>;
}

function ResourceEditorModal({ kind, item, branches, employees, pending, error, onClose, onSubmit }: { kind: "branch" | "atm" | "employee"; item?: any; branches: any[]; employees: any[]; pending: boolean; error?: string | undefined; onClose: () => void; onSubmit: (data: Record<string, string>) => void }) {
  const editing = Boolean(item);
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    onSubmit(Object.fromEntries([...new FormData(event.currentTarget).entries()].filter(([, value]) => String(value).trim())) as Record<string, string>);
  }
  const field = (name: string, label: string, value?: string | null, required = false) => <label className="text-[11px] font-bold text-bank-navy">{label}<input name={name} defaultValue={value ?? ""} required={required} className="mt-1.5 h-10 w-full rounded-lg border border-bank-border px-3 text-xs font-normal outline-none focus:border-bank-blue" /></label>;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-bank-dark/45"><form onSubmit={submit} className="max-h-[88vh] w-[620px] overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-lg font-extrabold capitalize text-bank-navy">{editing ? "Edit" : "Create"} {kind}</h2><p className="text-xs text-bank-muted">Changes are validated and recorded in the audit log.</p></div><button type="button" onClick={onClose}><X size={18} /></button></div>
    <div className="mt-5 grid grid-cols-2 gap-4">{kind === "branch" ? <>{!editing && field("branchCode", "Branch Code", "", true)}{field("branchName", "Branch Name", item?.branchName, true)}{field("address", "Address", item?.address)}{field("city", "City", item?.city)}{field("state", "State", item?.state)}{field("postalCode", "Postal Code", item?.postalCode)}{field("phone", "Phone", item?.phone)}{field("email", "Email", item?.email)}{field("operatingHours", "Operating Hours", item?.operatingHours)}{editing ? <label className="col-span-2 text-[11px] font-bold text-bank-navy">Manager<select name="managerId" defaultValue={item?.manager?.employeeId ?? ""} className="mt-1.5 h-10 w-full rounded-lg border px-3 text-xs font-normal"><option value="">No manager assigned</option>{employees.filter((employee) => employee.branch.branchId === item.branchId).map((employee) => <option key={employee.employeeId} value={employee.employeeId}>{employee.firstName} {employee.lastName} · {employee.position}</option>)}</select></label> : null}</> : null}
      {kind === "atm" ? <>{!editing && field("atmCode", "ATM Code", "", true)}{field("location", "Location", item?.location, true)}{field("operatingHours", "Operating Hours", item?.operatingHours)}{field("supportedTransactions", "Supported Transactions", item?.supportedTransactions)}<label className="text-[11px] font-bold text-bank-navy">Branch<select name="branchId" required defaultValue={item?.branch?.branchId ?? ""} className="mt-1.5 h-10 w-full rounded-lg border px-3 text-xs font-normal"><option value="">Select branch</option>{branches.map((branch) => <option key={branch.branchId} value={branch.branchId}>{branch.branchName}</option>)}</select></label>{!editing ? <label className="text-[11px] font-bold text-bank-navy">Status<select name="status" defaultValue="ACTIVE" className="mt-1.5 h-10 w-full rounded-lg border px-3 text-xs font-normal"><option>ACTIVE</option><option>MAINTENANCE</option><option>OUT_OF_SERVICE</option></select></label> : null}</> : null}
      {kind === "employee" ? <>{field("firstName", "First Name", item?.firstName, true)}{field("lastName", "Last Name", item?.lastName, true)}{field("email", "Email", item?.email)}{field("phone", "Phone", item?.phone)}<label className="text-[11px] font-bold text-bank-navy">Position<select name="position" defaultValue={item?.position ?? "Customer Service Officer"} className="mt-1.5 h-10 w-full rounded-lg border px-3 text-xs font-normal">{["Branch Manager","Customer Service Officer","Relationship Manager","Operations Officer","Cashier"].map((position) => <option key={position}>{position}</option>)}</select></label><label className="text-[11px] font-bold text-bank-navy">Branch<select name="branchId" required defaultValue={item?.branch?.branchId ?? ""} className="mt-1.5 h-10 w-full rounded-lg border px-3 text-xs font-normal">{branches.map((branch) => <option key={branch.branchId} value={branch.branchId}>{branch.branchName}</option>)}</select></label></> : null}</div>
    {error ? <p className="mt-3 text-xs text-red-600">{error}</p> : null}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="h-10 rounded-lg border px-4 text-xs font-bold">Cancel</button><button disabled={pending} className="inline-flex h-10 items-center gap-2 rounded-lg bg-bank-blue px-5 text-xs font-bold text-white disabled:opacity-60">{pending && <LoaderCircle size={14} className="animate-spin" />}{editing ? "Save Changes" : `Create ${kind}`}</button></div></form></div>;
}

export function AdminResourcePage({ resource }: { resource: AdminResource }) {
  const queryClient = useQueryClient();
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [searchInput, setSearchInput] = useState("");
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("");
  const [type, setType] = useState("");
  const [customer, setCustomer] = useState("");
  const [entity, setEntity] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [exporting, setExporting] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [employeeOpen, setEmployeeOpen] = useState(false);
  const [editor, setEditor] = useState<{ kind: "branch" | "atm" | "employee"; item?: any } | null>(null);
  const params: AdminQuery = { page, limit: pageSize, ...(search ? { search } : {}), ...(status ? { status } : {}), ...(type ? { type } : {}), ...(customer ? { customer } : {}), ...(entity ? { entity } : {}), ...(from ? { from } : {}), ...(to ? { to } : {}) };
  const listQuery = useQuery<AdminList<any>>({ queryKey: ["admin", resource, params], queryFn: async (): Promise<AdminList<any>> => {
    switch (resource) {
      case "customers": return adminApi.customers(params); case "accounts": return adminApi.accounts(params); case "transactions": return adminApi.transactions(params);
      case "employees": return adminApi.employees(params); case "branches": return adminApi.branches(params); case "atms": return adminApi.atms(params); case "cards": return adminApi.cards(params); default: return adminApi.auditLogs(params);
    }
  }, staleTime: 30_000 });
  const branchQuery = useQuery({ queryKey: ["admin", "branches", "options"], queryFn: () => adminApi.branches({ page: 1, limit: 100 }), enabled: ["employees", "branches", "atms"].includes(resource) });
  const employeeOptionsQuery = useQuery({ queryKey: ["admin", "employees", "options"], queryFn: () => adminApi.employees({ page: 1, limit: 100 }), enabled: resource === "branches" });
  const customerDetail = useQuery({ queryKey: ["admin", "customer", selectedId], queryFn: () => adminApi.customer(selectedId!), enabled: resource === "customers" && Boolean(selectedId) });
  const transactionDetail = useQuery({ queryKey: ["admin", "transaction", selectedId], queryFn: () => adminApi.transaction(selectedId!), enabled: resource === "transactions" && Boolean(selectedId) });
  const accountDetail = useQuery({ queryKey: ["admin", "account", selectedId], queryFn: () => adminApi.account(selectedId!), enabled: resource === "accounts" && Boolean(selectedId) });
  const actionMutation = useMutation({ mutationFn: async ({ kind, id, value }: { kind: string; id: string; value?: string }) => {
    if (kind === "customer") return adminApi.customerStatus(id, value as "ACTIVE" | "BLOCKED" | "INACTIVE");
    if (kind === "freeze") return adminApi.freezeAccount(id); if (kind === "unfreeze") return adminApi.unfreezeAccount(id);
    if (kind === "close") return adminApi.closeAccount(id);
    if (kind === "branchStatus") return adminApi.branchStatus(id, value as "ACTIVE" | "INACTIVE");
    if (kind === "atmStatus") return adminApi.atmStatus(id, value as "ACTIVE" | "MAINTENANCE" | "OUT_OF_SERVICE");
    return adminApi.employeeStatus(id, value as "ACTIVE" | "INACTIVE");
  }, onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["admin"] }); } });
  const createEmployee = useMutation({ mutationFn: adminApi.createEmployee, onSuccess: () => { setEmployeeOpen(false); void queryClient.invalidateQueries({ queryKey: ["admin", "employees"] }); } });
  const editorMutation = useMutation({ mutationFn: async ({ current, data }: { current: NonNullable<typeof editor>; data: Record<string, string> }) => {
    if (current.kind === "branch") {
      const { managerId, ...branchData } = data;
      const saved: any = current.item ? await adminApi.updateBranch(current.item.branchId, branchData) : await adminApi.createBranch(branchData);
      if (current.item) await adminApi.branchManager(current.item.branchId, managerId || null);
      return saved;
    }
    if (current.kind === "atm") return current.item ? adminApi.updateAtm(current.item.atmId, data) : adminApi.createAtm(data);
    return adminApi.updateEmployee(current.item.employeeId, data);
  }, onSuccess: () => { setEditor(null); void queryClient.invalidateQueries({ queryKey: ["admin"] }); } });
  const rows = listQuery.data?.items ?? [];
  const pagination = listQuery.data?.pagination;
  const selected: any = resource === "customers" ? customerDetail.data : resource === "transactions" ? transactionDetail.data : resource === "accounts" ? accountDetail.data : rows.find((item: any) => (item.branchId ?? item.employeeId ?? item.atmId) === selectedId);
  const columns = useMemo(() => {
    switch (resource) {
      case "customers": return ["Customer", "Customer ID", "Branch", "KYC", "Status", "Actions"];
      case "accounts": return ["Account", "Owner", "Type", "Balance", "Branch", "Status / Actions"];
      case "transactions": return ["Reference", "Type", "From / To", "Amount", "Status", "Date / Action"];
      case "employees": return ["Employee", "Number", "Position", "Branch", "Status", "Action"];
      case "branches": return ["Branch", "Location", "Manager", "Customers", "Employees / ATMs", "Status / Actions"];
      case "atms": return ["ATM", "Location", "Branch", "Hours", "Services", "Status / Actions"];
      case "cards": return ["Card", "Owner", "Account", "Type", "Created", "Status"];
      default: return ["User", "Action", "Entity", "Entity ID", "Reason", "IP", "Timestamp"];
    }
  }, [resource]);
  const cell = "px-4 py-3 text-[11px] text-bank-text";
  function renderRow(item: any) {
    if (resource === "customers") return <><td className={cell}><b>{item.firstName} {item.lastName}</b><span className="mt-0.5 block text-[10px] text-bank-muted">{item.email}</span></td><td className={cell}>{item.customerNumber}</td><td className={cell}>{item.branch.branchName}</td><td className={cell}><Status value={item.kycStatus} /></td><td className={cell}><Status value={item.customerStatus} /></td><td className={cell}><div className="flex gap-2"><button onClick={() => setSelectedId(item.customerId)} className="text-bank-blue"><Eye size={15} /></button><button disabled={actionMutation.isPending} onClick={() => actionMutation.mutate({ kind: "customer", id: item.customerId, value: item.customerStatus === "ACTIVE" ? "BLOCKED" : "ACTIVE" })} className="rounded-md border px-2 py-1 font-bold text-bank-navy">{item.customerStatus === "ACTIVE" ? "Block" : "Unblock"}</button></div></td></>;
    if (resource === "accounts") return <><td className={cell}><b>{item.maskedAccountNumber}</b></td><td className={cell}>{item.customer.firstName} {item.customer.lastName}<span className="block text-[10px] text-bank-muted">{item.customer.customerNumber}</span></td><td className={cell}>{item.accountType}</td><td className={cell}><b>{inr.format(Number(item.currentBalance))}</b></td><td className={cell}>{item.branch.branchName}</td><td className={cell}><div className="flex items-center gap-2"><Status value={item.accountStatus} />{item.accountStatus !== "CLOSED" ? <button disabled={actionMutation.isPending} onClick={() => actionMutation.mutate({ kind: item.accountStatus === "FROZEN" ? "unfreeze" : "freeze", id: item.accountId })} className="rounded-md border px-2 py-1 font-bold">{item.accountStatus === "FROZEN" ? "Unfreeze" : "Freeze"}</button> : null}{Number(item.currentBalance) === 0 && item.accountStatus !== "CLOSED" ? <button onClick={() => actionMutation.mutate({ kind: "close", id: item.accountId })} className="rounded-md border border-red-200 px-2 py-1 font-bold text-red-600">Close</button> : null}</div></td></>;
    if (resource === "transactions") return <><td className={cell}><b>{item.referenceNumber}</b></td><td className={cell}>{item.transactionType}</td><td className={cell}><span className="block">{item.sourceAccount ?? "External"}</span><span className="text-bank-muted">→ {item.destinationAccount ?? "External"}</span></td><td className={cell}><b>{inr.format(Number(item.amount))}</b></td><td className={cell}><Status value={item.status} /></td><td className={cell}>{dateTime(item.initiatedAt)}<button onClick={() => setSelectedId(item.transactionId)} className="ml-3 text-bank-blue"><Eye size={15} /></button></td></>;
    if (resource === "employees") return <><td className={cell}><b>{item.firstName} {item.lastName}</b><span className="block text-[10px] text-bank-muted">{item.email}<br />{item.phone}</span></td><td className={cell}>{item.employeeNumber}</td><td className={cell}>{item.position ?? "—"}</td><td className={cell}>{item.branch.branchName}</td><td className={cell}><Status value={item.status} /></td><td className={cell}><div className="flex gap-2"><button onClick={() => setEditor({ kind: "employee", item })} className="text-bank-blue"><Pencil size={15} /></button><button onClick={() => actionMutation.mutate({ kind: "employee", id: item.employeeId, value: item.status === "ACTIVE" ? "INACTIVE" : "ACTIVE" })} className="rounded-md border px-2 py-1 font-bold">{item.status === "ACTIVE" ? "Deactivate" : "Activate"}</button></div></td></>;
    if (resource === "branches") return <><td className={cell}><b>{item.branchName}</b><span className="block text-[10px] text-bank-muted">{item.branchCode}</span></td><td className={cell}>{item.city}, {item.state}<span className="block text-[10px] text-bank-muted">{item.address}</span></td><td className={cell}>{item.manager?.name ?? "Not assigned"}</td><td className={cell}>{item.counts.customers}</td><td className={cell}><span className="block">{item.employees.map((employee: any) => employee.name).join(", ") || "No employees"}</span><span className="mt-1 block text-[10px] text-bank-muted">ATMs: {item.atms.map((atm: any) => atm.atmCode).join(", ") || "None"}</span></td><td className={cell}><div className="flex items-center gap-2"><Status value={item.status} /><button onClick={() => setEditor({ kind: "branch", item })} className="text-bank-blue"><Pencil size={15} /></button><button onClick={() => actionMutation.mutate({ kind: "branchStatus", id: item.branchId, value: item.status === "ACTIVE" ? "INACTIVE" : "ACTIVE" })} className="rounded-md border px-2 py-1 font-bold">{item.status === "ACTIVE" ? "Deactivate" : "Activate"}</button></div></td></>;
    if (resource === "atms") return <><td className={cell}><b>{item.atmCode}</b></td><td className={cell}>{item.location}</td><td className={cell}>{item.branch.branchName}</td><td className={cell}>{item.operatingHours ?? "—"}</td><td className={`${cell} max-w-56 truncate`}>{item.supportedTransactions ?? "—"}</td><td className={cell}><div className="flex items-center gap-2"><Status value={item.status} /><button onClick={() => setEditor({ kind: "atm", item })} className="text-bank-blue"><Pencil size={15} /></button><select value={item.status} onChange={(event) => actionMutation.mutate({ kind: "atmStatus", id: item.atmId, value: event.target.value })} className="h-7 rounded border px-1 text-[9px]"><option>ACTIVE</option><option>MAINTENANCE</option><option>OUT_OF_SERVICE</option></select></div></td></>;
    if (resource === "cards") return <><td className={cell}><b>{item.maskedCardNumber}</b><span className="block text-[10px] text-bank-muted">{item.cardReference}</span></td><td className={cell}>{item.customer.name}<span className="block text-[10px] text-bank-muted">{item.customer.customerNumber}</span></td><td className={cell}>{item.account.accountType} {item.account.maskedAccountNumber}</td><td className={cell}>{item.cardType}</td><td className={cell}>{dateTime(item.createdAt)}</td><td className={cell}><Status value={item.cardStatus} /></td></>;
    return <><td className={cell}><b>{item.user.name}</b><span className="block text-[10px] text-bank-muted">{item.user.email}</span></td><td className={cell}>{item.action}</td><td className={cell}>{item.entity}</td><td className={cell}>{item.entityId}</td><td className={`${cell} max-w-48 truncate`}>{item.reason ?? "—"}</td><td className={cell}>{item.ipAddress}</td><td className={cell}>{dateTime(item.createdAt)}</td></>;
  }
  const pageMeta = meta[resource];
  async function exportTransactions() { setExporting(true); try { const items = await adminApi.allTransactions(params); downloadCsv(`transactions_${reportDate()}.csv`, ["Transaction Reference","Date","Customer","Source Account","Destination Account","Type","Amount","Status","Remarks"], items.map((item) => [item.referenceNumber,item.initiatedAt,item.source?.customerName ?? item.destination?.customerName ?? "External",item.sourceAccount,item.destinationAccount,item.transactionType,item.amount,item.status,item.description])); } finally { setExporting(false); } }
  const headerAction = resource === "employees" ? <button onClick={() => setEmployeeOpen(true)} className="inline-flex h-9 items-center gap-2 rounded-lg bg-bank-blue px-4 text-xs font-bold text-white"><Plus size={15} />Create Employee</button> : resource === "branches" ? <button onClick={() => setEditor({ kind: "branch" })} className="inline-flex h-9 items-center gap-2 rounded-lg bg-bank-blue px-4 text-xs font-bold text-white"><Plus size={15} />Create Branch</button> : resource === "atms" ? <button onClick={() => setEditor({ kind: "atm" })} className="inline-flex h-9 items-center gap-2 rounded-lg bg-bank-blue px-4 text-xs font-bold text-white"><Plus size={15} />Create ATM</button> : undefined;
  return <AdminLayout title={pageMeta.title} subtitle={pageMeta.subtitle} action={headerAction}>
    <section className="rounded-2xl border border-bank-border bg-white shadow-[0_6px_22px_rgba(11,31,58,0.04)]"><div className="flex flex-wrap items-center gap-2 border-b border-bank-border p-4"><form onSubmit={(event) => { event.preventDefault(); setPage(1); setSearch(searchInput.trim()); }} className="relative w-[280px]"><Search size={15} className="absolute left-3 top-3 text-bank-muted" /><input value={searchInput} onChange={(event) => setSearchInput(event.target.value)} placeholder={pageMeta.search} className="h-10 w-full rounded-lg border border-bank-border pl-9 pr-3 text-xs outline-none focus:border-bank-blue" /></form>{resource !== "audit-logs" ? <select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} className="h-10 rounded-lg border border-bank-border px-3 text-xs"><option value="">All statuses</option><option>ACTIVE</option><option>INACTIVE</option>{resource === "customers" && <option>BLOCKED</option>}{resource === "accounts" && <option>FROZEN</option>}{resource === "transactions" && <><option>PROCESSING</option><option>COMPLETED</option><option>FAILED</option><option>REVERSED</option></>}{resource === "atms" && <><option>MAINTENANCE</option><option>OUT_OF_SERVICE</option></>}</select> : null}{["accounts","transactions","cards","audit-logs"].includes(resource) ? <input value={type} onChange={(event) => { setType(event.target.value.toUpperCase()); setPage(1); }} placeholder="Type / action" className="h-10 w-36 rounded-lg border border-bank-border px-3 text-xs" /> : null}{resource==="transactions"?<input value={customer} onChange={e=>{setCustomer(e.target.value);setPage(1)}} placeholder="Customer" className="h-10 w-32 rounded-lg border px-3 text-xs"/>:null}{resource==="audit-logs"?<input value={entity} onChange={e=>{setEntity(e.target.value.toUpperCase());setPage(1)}} placeholder="Entity type" className="h-10 w-32 rounded-lg border px-3 text-xs"/>:null}{["transactions","audit-logs"].includes(resource)?<><input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}} className="h-10 rounded-lg border px-2 text-xs"/><input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}} className="h-10 rounded-lg border px-2 text-xs"/></>:null}<select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}} className="h-10 rounded-lg border px-2 text-xs">{[10,25,50].map(n=><option key={n}>{n}</option>)}</select>{resource==="transactions"?<button disabled={exporting} onClick={()=>void exportTransactions()} className="flex h-10 items-center gap-2 rounded-lg border px-3 text-xs font-bold text-bank-blue"><Download size={14}/>{exporting?"Exporting…":"Export CSV"}</button>:null}<span className="ml-auto text-[10px] font-semibold text-bank-muted">{pagination?.total ?? 0} records</span></div>
      {listQuery.isLoading ? <div className="space-y-2 p-4">{Array.from({ length: 7 }, (_, i) => <div key={i} className="h-12 animate-pulse rounded-lg bg-slate-50" />)}</div> : listQuery.isError ? <div className="p-10 text-center text-xs text-red-600">{getApiErrorMessage(listQuery.error)} <button onClick={() => listQuery.refetch()} className="ml-2 font-bold text-bank-blue">Retry</button></div> : rows.length === 0 ? <div className="p-12 text-center text-xs text-bank-muted">No matching records found.</div> : <div className="overflow-x-auto"><table className="w-full border-collapse"><thead><tr className="bg-slate-50">{columns.map((column) => <th key={column} className="px-4 py-3 text-left text-[9px] font-extrabold uppercase tracking-[0.12em] text-bank-muted">{column}</th>)}</tr></thead><tbody>{rows.map((item: any, index) => <tr key={item.customerId ?? item.accountId ?? item.transactionId ?? item.employeeId ?? item.branchId ?? item.atmId ?? item.cardId ?? item.auditId ?? index} className="border-t border-bank-border hover:bg-slate-50/60">{renderRow(item)}</tr>)}</tbody></table></div>}
      {pagination && pagination.totalPages > 1 ? <div className="flex items-center justify-between border-t border-bank-border p-4 text-xs"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-40">Previous</button><span className="text-bank-muted">Page {pagination.page} of {pagination.totalPages}</span><button disabled={page >= pagination.totalPages} onClick={() => setPage((value) => value + 1)} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-40">Next</button></div> : null}
    </section>
    {selectedId ? <div className="fixed inset-0 z-40 bg-bank-dark/25" onClick={() => setSelectedId(null)}>
      <aside className="absolute right-0 top-0 h-full w-[460px] overflow-y-auto bg-white p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}>
        <button onClick={() => setSelectedId(null)} className="absolute right-5 top-5"><X size={19} /></button>
        {customerDetail.isLoading || transactionDetail.isLoading ? <LoaderCircle className="mx-auto mt-20 animate-spin text-bank-blue" /> : selected ? <div>
          <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-bank-blue">{resource === "customers" ? "Customer details" : "Transaction details"}</p>
          <h2 className="mt-2 text-xl font-extrabold text-bank-navy">{resource === "customers" ? `${selected.firstName} ${selected.lastName}` : selected.referenceNumber}</h2>
          {resource === "customers" ? <div className="mt-6 space-y-5 text-xs">
            <p><b>Customer ID</b><span className="block text-bank-muted">{selected.customerNumber}</span></p><p><b>Email</b><span className="block text-bank-muted">{selected.email}</span></p><p><b>Branch</b><span className="block text-bank-muted">{selected.branch.branchName}</span></p>
            <div><b>Accounts</b>{selected.accounts?.map((account: any) => <div key={account.accountId} className="mt-2 rounded-xl border p-3"><div className="flex justify-between"><span>{account.accountType} {account.maskedAccountNumber}</span><Status value={account.accountStatus} /></div><b className="mt-2 block">{inr.format(Number(account.currentBalance))}</b></div>)}</div>
            <div><b>Cards</b>{selected.cards?.length ? selected.cards.map((card: any) => <div key={card.cardId} className="mt-2 flex justify-between rounded-xl border p-3"><span>{card.cardType} {card.maskedCardNumber}</span><Status value={card.cardStatus} /></div>) : <p className="mt-2 text-bank-muted">No cards.</p>}</div>
            <div><b>Recent Transactions</b>{selected.transactions?.length ? selected.transactions.slice(0, 5).map((transaction: any) => <div key={transaction.transactionId} className="mt-2 flex justify-between rounded-xl border p-3"><span>{transaction.transactionType}<small className="block text-bank-muted">{transaction.referenceNumber}</small></span><b>{inr.format(Number(transaction.amount))}</b></div>) : <p className="mt-2 text-bank-muted">No transactions.</p>}</div>
          </div> : <div className="mt-6 space-y-4 text-xs"><p><b>Amount</b><span className="block text-lg text-bank-navy">{inr.format(Number(selected.amount))}</span></p><p><b>Type / Status</b><span className="block text-bank-muted">{selected.transactionType} · {selected.status}</span></p><p><b>From</b><span className="block text-bank-muted">{selected.source ? `${selected.source.customerName} · ${selected.source.maskedAccountNumber}` : "External"}</span></p><p><b>To</b><span className="block text-bank-muted">{selected.destination ? `${selected.destination.customerName} · ${selected.destination.maskedAccountNumber}` : "External"}</span></p><p><b>Date</b><span className="block text-bank-muted">{dateTime(selected.initiatedAt)}</span></p><p><b>Description</b><span className="block text-bank-muted">{selected.details?.[0]?.description ?? selected.details?.[0]?.merchant_payee ?? "—"}</span></p></div>}
        </div> : <p className="mt-20 text-center text-xs text-red-600">Unable to load details.</p>}
      </aside>
    </div> : null}
    <EmployeeModal open={employeeOpen} branches={branchQuery.data?.items ?? []} pending={createEmployee.isPending} error={createEmployee.isError ? getApiErrorMessage(createEmployee.error) : undefined} onClose={() => { setEmployeeOpen(false); createEmployee.reset(); }} onSubmit={(data) => createEmployee.mutate(data)} />
    {editor ? <ResourceEditorModal kind={editor.kind} item={editor.item} branches={branchQuery.data?.items ?? []} employees={employeeOptionsQuery.data?.items ?? []} pending={editorMutation.isPending} error={editorMutation.isError ? getApiErrorMessage(editorMutation.error) : undefined} onClose={() => { setEditor(null); editorMutation.reset(); }} onSubmit={(data) => editorMutation.mutate({ current: editor, data })} /> : null}
  </AdminLayout>;
}
