import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { adminApi } from "@/api/adminApi";
import { AdminLayout } from "@/components/admin/admin-layout";
import { actionButton, AdminModal, Field, StatusBadge, dateTime } from "@/components/admin/admin-ui";
import { getApiErrorMessage } from "@/lib/apiClient";

export function AdminCardRequestsPage(){
  const[status,setStatus]=useState(""); const[action,setAction]=useState<{kind:"review"|"approve"|"reject";item:any}|null>(null); const qc=useQueryClient();
  const query=useQuery({queryKey:["admin","card-requests",status],queryFn:()=>adminApi.cardRequests({page:1,limit:100,...(status?{status}:{})})});
  const mutation=useMutation({mutationFn:async(values:Record<string,string>)=>{if(!action)throw Error("ACTION_REQUIRED");const id=String(action.item.card_request_id);if(action.kind==="review")return adminApi.reviewCardRequest(id);if(action.kind==="approve")return adminApi.approveCardRequest(id);return adminApi.rejectCardRequest(id,values.reason)},onSuccess:()=>{setAction(null);void qc.invalidateQueries({queryKey:["admin"]})}});
  const rows=query.data?.items??[];
  return <AdminLayout title="Card Requests" subtitle="Review and approve customer card applications"><section className="rounded-2xl border bg-white"><div className="border-b p-4"><select value={status} onChange={event=>setStatus(event.target.value)} className="h-10 rounded-lg border px-3 text-xs"><option value="">All statuses</option>{["PENDING","UNDER_REVIEW","APPROVED","REJECTED","CANCELLED"].map(value=><option key={value}>{value}</option>)}</select></div>{query.isLoading?<p className="p-10 text-center text-xs">Loading requests…</p>:query.isError?<p className="p-10 text-center text-xs text-red-600">{getApiErrorMessage(query.error)}</p>:!rows.length?<p className="p-10 text-center text-xs text-bank-muted">No card requests.</p>:<table className="w-full text-left text-[10px]"><thead className="bg-slate-50"><tr>{["Customer","Customer ID","Account","Card Type","Requested","Status","Actions"].map(value=><th className="px-3 py-3" key={value}>{value}</th>)}</tr></thead><tbody>{rows.map((item:any)=><tr className="border-t" key={item.card_request_id}><td className="px-3 py-3">{item.customers.first_name} {item.customers.last_name}</td><td>{item.customers.customer_number}</td><td>{item.accounts.account_type} ****{item.accounts.account_number.slice(-4)}</td><td>{item.card_type}</td><td>{dateTime(item.created_at)}</td><td><StatusBadge value={item.status}/>{item.rejection_reason?<small className="block text-red-600">{item.rejection_reason}</small>:null}</td><td><div className="flex gap-1">{item.status==="PENDING"?<button className={actionButton} onClick={()=>setAction({kind:"review",item})}>Start Review</button>:null}{item.status==="UNDER_REVIEW"?<button className={actionButton} onClick={()=>setAction({kind:"approve",item})}>Approve</button>:null}{["PENDING","UNDER_REVIEW"].includes(item.status)?<button className={actionButton} onClick={()=>setAction({kind:"reject",item})}>Reject</button>:null}</div></td></tr>)}</tbody></table>}</section>{action?<AdminModal title={`${action.kind} card request`} pending={mutation.isPending} error={mutation.isError?getApiErrorMessage(mutation.error):undefined} submitLabel="Confirm" onClose={()=>setAction(null)} onSubmit={values=>mutation.mutate(values)}>{action.kind==="reject"?<Field name="reason" label="Rejection Reason" minLength={3}/>:<p className="text-xs text-bank-muted">This action is validated and audited by the backend.</p>}</AdminModal>:null}</AdminLayout>;
}
