import { useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { useSearchParams } from "react-router-dom";
import { adminApi } from "@/api/adminApi";
import { AdminLayout } from "@/components/admin/admin-layout";
import { AdminModal,Field,StatusBadge,actionButton,dateTime,inr } from "@/components/admin/admin-ui";
import { AdminPagination } from "@/components/admin/admin-pagination";
import { getApiErrorMessage } from "@/lib/apiClient";
type Action={type:"review"|"approve"|"reject";item:any};
export function AdminLoanRequestsPage(){
 const[p]=useSearchParams();const qc=useQueryClient();const[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[status,setStatus]=useState(p.get("status")??"");const[action,setAction]=useState<Action|null>(null);
 const query=useQuery({queryKey:["admin","loan-requests",{page,pageSize,status}],queryFn:()=>adminApi.loanRequests({page,limit:pageSize,...(status?{status}:{})})});
 const mutation=useMutation({mutationFn:async(v:Record<string,string>)=>{if(!action)return;if(action.type==="review")return adminApi.reviewLoanRequest(String(action.item.loan_request_id));if(action.type==="reject")return adminApi.rejectLoanRequest(String(action.item.loan_request_id),v.reason);return adminApi.approveLoanRequest(String(action.item.loan_request_id),{approvedAmount:Number(v.approvedAmount),approvedDurationMonths:Number(v.approvedDurationMonths)});},onSuccess:()=>{setAction(null);void qc.invalidateQueries({queryKey:["admin"]});}});
 const rows=query.data?.items??[];
 return <AdminLayout title="Loan Requests" subtitle="Paginated lending requests"><section className="rounded-2xl border bg-white"><div className="border-b p-4"><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="h-10 rounded-lg border px-3 text-xs"><option value="">All statuses</option>{["PENDING","UNDER_REVIEW","APPROVED","REJECTED","CANCELLED"].map(x=><option key={x}>{x}</option>)}</select></div>{query.isLoading?<p className="p-10 text-center text-xs">Loading requests…</p>:query.isError?<p className="p-10 text-center text-xs text-red-600">{getApiErrorMessage(query.error)}</p>:!rows.length?<p className="p-10 text-center text-xs text-bank-muted">No matching requests.</p>:<table className="w-full text-left text-[10px]"><thead className="bg-slate-50"><tr>{["Customer","Amount","Duration","Product","Purpose","Status","Submitted","Updated","Actions"].map(h=><th className="px-3 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r:any)=><tr className="border-t" key={r.loan_request_id}><td className="px-3 py-3">{r.customers.first_name} {r.customers.last_name}</td><td>{inr.format(Number(r.requested_amount))}</td><td>{r.requested_duration_months} months</td><td>{r.loan_type}</td><td>{r.purpose}</td><td><StatusBadge value={r.status}/>{r.rejection_reason?<small className="block text-red-600">{r.rejection_reason}</small>:null}</td><td>{dateTime(r.created_at)}</td><td>{dateTime(r.updated_at)}</td><td><div className="flex gap-1">{r.status==="PENDING"?<button className={actionButton} onClick={()=>setAction({type:"review",item:r})}>Review</button>:null}{r.status==="UNDER_REVIEW"?<button className={actionButton} onClick={()=>setAction({type:"approve",item:r})}>Approve</button>:null}{["PENDING","UNDER_REVIEW"].includes(r.status)?<button className={actionButton} onClick={()=>setAction({type:"reject",item:r})}>Reject</button>:null}</div></td></tr>)}</tbody></table>}<AdminPagination pagination={query.data?.pagination} page={page} pageSize={pageSize} onPage={setPage} onPageSize={n=>{setPageSize(n);setPage(1)}}/></section>{action?<AdminModal title={`${action.type} loan request`} pending={mutation.isPending} error={mutation.isError?getApiErrorMessage(mutation.error):undefined} submitLabel="Confirm" onClose={()=>setAction(null)} onSubmit={v=>mutation.mutate(v)}>{action.type==="approve"?<><Field name="approvedAmount" label="Approved Amount" type="number" defaultValue={Number(action.item.requested_amount)}/><p className="text-xs text-bank-muted">Configured rate: {Number(action.item.requested_interest_rate).toFixed(2)}% p.a. The backend recalculates it for the approved duration.</p><Field name="approvedDurationMonths" label="Duration" type="number" defaultValue={action.item.requested_duration_months}/></>:action.type==="reject"?<Field name="reason" label="Reason"/>:<p className="text-xs text-bank-muted">Move this request to review?</p>}</AdminModal>:null}</AdminLayout>;
}
